repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.3.1
  hooks:
    - id: sqlfluff-lint
      additional_dependencies: 
        - sqlfluff-templater-dbt==3.3.1
        - dbt-postgres==1.9.0
      
    - id: sqlfluff-fix
      additional_dependencies:
        - sqlfluff-templater-dbt==3.3.1
        - dbt-postgres==1.9.0